# Generated by Django 3.0.10 on 2020-09-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200909_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupcakespage',
            name='days_available',
            field=models.CharField(choices=[('Weekends Only', 'Weekends Only'), ('Monday-Friday', 'Monday-Friday'), ('Tuesday/Thursday', 'Tuesday/Thursday'), ('Seasonal', 'Seasonal')], default='', max_length=20),
        ),
    ]
