# Generated by Django 2.1.4 on 2019-01-02 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20181214_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formpagefield',
            options={'ordering': ['sort_order']},
        ),
    ]
