dist: xenial
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -e './[ci]'
  - pip install codecov
before_script:
  - coderedcms start testproject
# command to run tests
script:
  - coverage run testproject/manage.py test coderedcms --settings=coderedcms.tests.settings
  - flake8 coderedcms testproject --exit-zero
after_success:
  - codecov
