# Generated by Django 3.2.7 on 2021-09-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_indextestpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventindexpage',
            name='event_style',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('block', 'Solid rectangles'), ('list-item', 'Dots with labels')], default='', help_text='How events look on the calendar.', max_length=255, verbose_name='Event Style'),
        ),
        migrations.AlterField(
            model_name='eventindexpage',
            name='default_calendar_view',
            field=models.CharField(blank=True, choices=[('', 'No calendar'), ('month', 'Month'), ('agendaWeek', 'Week'), ('agendaDay', 'Day'), ('listMonth', 'List of events')], default='month', help_text='The default look of the calendar on this page.', max_length=255, verbose_name='Calendar Style'),
        ),
    ]
