# Generated by Django 2.1.8 on 2019-04-08 22:20

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coderedcms', '0013_classifiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifierterm',
            name='classifier',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifier_terms', to='coderedcms.Classifier', verbose_name='Classifier'),
        ),
    ]
