# Generated by Django 2.2 on 2019-04-30 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_flexible_forms', '__first__'),
        ('coderedcms', '0014_classifiers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoderedSessionFormSubmission',
            fields=[
            ],
            options={
                'constraints': [],
                'proxy': True,
                'indexes': [],
            },
            bases=('wagtail_flexible_forms.sessionformsubmission',),
        ),
    ]
