# Generated by Django 2.2.2 on 2019-06-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderedcms', '0015_coderedsessionformsubmission_coderedsubmissionrevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='layoutsettings',
            name='navbar_name',
            field=models.CharField(blank=True, help_text='Is necessary to associante to when you create a NavBar fragments.', max_length=50, verbose_name='Navbar name'),
        ),
    ]
