# Generated by Django 2.2.2 on 2019-06-30 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coderedcms', '0016_layoutsettings_navbar_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='layoutsetting',
            field=models.ForeignKey(blank=True, help_text='The Layout page users to determinate a site owner Navigation Bar Manu.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='coderedcms.LayoutSettings', verbose_name='Layout Page'),
        ),
        migrations.AlterField(
            model_name='layoutsettings',
            name='navbar_name',
            field=models.CharField(blank=True, help_text='It is necessary to associate when you create a Navigation Bar fragments.', max_length=50, verbose_name='Navbar name'),
        ),
    ]
