# Generated by Django 3.1.7 on 2021-02-25 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coderedcms', '0019_spelling_corrections'),
    ]

    operations = [
        migrations.AddField(
            model_name='layoutsettings',
            name='navbar_chooser',
            field=models.ForeignKey(blank=True, help_text='Choose the navbar snippet that you want to use for this site.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nav', to='coderedcms.navbar', verbose_name='Site Navbar'),
        ),
    ]
