# Generated by Django 3.1.7 on 2021-04-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderedcms', '0019_spelling_corrections'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticssettings',
            name='below_body_scripts',
            field=models.TextField(blank=True, null=True, verbose_name='Add tracking scripts toward closing <body> tag.'),
        ),
        migrations.AddField(
            model_name='analyticssettings',
            name='below_head_scripts',
            field=models.TextField(blank=True, null=True, verbose_name='Add tracking scripts between the <head> tags.'),
        ),
    ]
