# Generated by Django 3.1.7 on 2021-03-01 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coderedcms', '0020_layoutsettings_navbar_chooser'),
    ]

    operations = [
        migrations.AddField(
            model_name='layoutsettings',
            name='footer_chooser',
            field=models.ForeignKey(blank=True, help_text='Choose the footer snippet that you want to use for this site.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_footer', to='coderedcms.footer', verbose_name='Site Footer'),
        ),
        migrations.AlterField(
            model_name='layoutsettings',
            name='navbar_chooser',
            field=models.ForeignKey(blank=True, help_text='Choose the navbar snippet that you want to use for this site.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_nav', to='coderedcms.navbar', verbose_name='Site Navbar'),
        ),
    ]
