# Generated by Django 3.1.7 on 2021-03-16 14:57

from django.db import migrations


def add_navbar_orderables(apps, schema_editor):
    Site = apps.get_model('wagtailcore', 'Site')
    LayoutSettings = apps.get_model('coderedcms', 'LayoutSettings')
    Navbar = apps.get_model('coderedcms', 'Navbar')
    NavbarOrderable = apps.get_model('coderedcms', 'NavbarOrderable')
    # If it's a new site, this migration will not run.
    try:
        site = Site.objects.get(is_default_site=True)
        layout = LayoutSettings.objects.get(site=site)
    except (Site.DoesNotExist, LayoutSettings.DoesNotExist):
        return
    current_navs = Navbar.objects.all()
    db_alias = schema_editor.connection.alias
    layout.site_navbar = []
    layout.save()
    for nav in current_navs:
        NavbarOrderable.objects.using(db_alias).create(navbar_chooser=layout, navbar=nav)


def add_footer_orderables(apps, schema_editor):
    Site = apps.get_model('wagtailcore', 'Site')
    LayoutSettings = apps.get_model('coderedcms', 'LayoutSettings')
    Footer = apps.get_model('coderedcms', 'Footer')
    FooterOrderable = apps.get_model('coderedcms', 'FooterOrderable')
    # If it's a new site, this migration will not run.
    try:
        site = Site.objects.get(is_default_site=True)
        layout = LayoutSettings.objects.get(site=site)
    except (Site.DoesNotExist, LayoutSettings.DoesNotExist):
        return
    current_footers = Footer.objects.all()
    db_alias = schema_editor.connection.alias
    layout.site_footer = []
    layout.save()
    for footer in current_footers:
        FooterOrderable.objects.using(db_alias).create(footer_chooser=layout, footer=footer)



class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('coderedcms', '0020_footerorderable_navbarorderable'),
    ]

    operations = [
        migrations.RunPython(add_navbar_orderables),
        migrations.RunPython(add_footer_orderables)
    ]
