# Generated by Django 3.2.13 on 2022-05-11 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcrx', '0024_analyticssettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMediaSettings',
        ),
    ]
