# Generated by Django 3.2.13 on 2022-06-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderedcms', '0027_auto_20220603_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='animation',
            field=models.CharField(blank=True, default='', help_text='The animation when transitioning between slides.', max_length=20, verbose_name='Animation'),
        ),
        migrations.AlterField(
            model_name='layoutsettings',
            name='frontend_theme',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Theme variant'),
        ),
        migrations.AlterField(
            model_name='layoutsettings',
            name='navbar_class',
            field=models.CharField(blank=True, default='', help_text='Custom classes applied to navbar e.g. "bg-light", "bg-dark", "bg-primary".', max_length=255, verbose_name='Navbar CSS class'),
        ),
        migrations.AlterField(
            model_name='layoutsettings',
            name='navbar_collapse_mode',
            field=models.CharField(blank=True, default='', help_text='Control on what screen sizes to show and collapse the navbar menu links.', max_length=50, verbose_name='Collapse navbar menu'),
        ),
        migrations.AlterField(
            model_name='layoutsettings',
            name='navbar_color_scheme',
            field=models.CharField(blank=True, default='', help_text='Optimizes text and other navbar elements for use with light or dark backgrounds.', max_length=50, verbose_name='Navbar color scheme'),
        ),
        migrations.AlterField(
            model_name='layoutsettings',
            name='navbar_format',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Navbar format'),
        ),
    ]
