# Generated by Django 3.2.13 on 2022-07-18 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coderedcms', '0030_alter_coderedtag_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accordion',
            fields=[
                ('reusablecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coderedcms.reusablecontent')),
            ],
            options={
                'verbose_name': 'Accordion',
                'verbose_name_plural': 'Accordions',
            },
            bases=('coderedcms.reusablecontent',),
        ),
    ]
