# Generated by Django 4.0.6 on 2022-08-01 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderedcms', '0031_accordion_accordionpanel'),
        ('coderedcms', '0031_wagtail3'),
    ]

    operations = [
    ]
