# Generated by Django 4.0.7 on 2022-08-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderedcms', '0033_remove_carousel_animation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ADASettings',
        ),
    ]
