# Generated by Django 4.1.8 on 2023-04-13 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coderedcms", "0036_filmstrip_filmpanel"),
    ]

    operations = [
        migrations.AddField(
            model_name="coderedpage",
            name="related_classifier_term",
            field=models.ForeignKey(
                blank=True,
                help_text="When getting related pages, pages with this term will be weighted over other classifier terms. By default, pages with the greatest number of classifiers in common are ranked highest.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="coderedcms.classifierterm",
                verbose_name="Preferred related classifier term",
            ),
        ),
        migrations.AddField(
            model_name="coderedpage",
            name="related_num",
            field=models.PositiveIntegerField(
                default=3, verbose_name="Number of related pages to show"
            ),
        ),
        migrations.AddField(
            model_name="coderedpage",
            name="related_show",
            field=models.BooleanField(
                default=False, verbose_name="Show list of related pages"
            ),
        ),
    ]
