# Generated by Django 4.0.6 on 2023-04-12 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coderedcms', '0036_filmstrip_filmpanel'),
    ]

    operations = [
        migrations.AddField(
            model_name='coderedpage',
            name='preferred_related_classifier_term',
            field=models.ForeignKey(blank=True, help_text='When getting related pages for this page, pages with this classifier will be weighted over other classifier terms.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='coderedcms.classifierterm', verbose_name='Preferred Related Classifier Term'),
        ),
    ]
