# Generated by Django 4.1.10 on 2023-07-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coderedcms", "0037_coderedpage_related_classifier_term_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classifier",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                max_length=255,
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
