# Generated by Django 3.2.18 on 2023-05-05 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('coderedcms', '0037_coderedpage_related_classifier_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reusablecontent',
            name='latest_revision',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision'),
        ),
    ]
