# Generated by Django 4.1.10 on 2023-07-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coderedcms", "0038_alter_classifier_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classifierterm",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                max_length=255,
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
