# Generated by Django 4.1.12 on 2023-10-20 16:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coderedcms", "0039_alter_classifierterm_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analyticssettings",
            name="ga_tracking_id",
        ),
    ]
