# Generated by Django 4.2 on 2024-05-29 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coderedcms", "0040_remove_analyticssettings_ga_tracking_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="layoutsettings",
            name="frontend_theme",
        ),
    ]
