# Generated by Django 5.0.7 on 2024-07-16 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coderedcms", "0041_remove_layoutsettings_frontend_theme"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layoutsettings",
            name="favicon",
            field=models.ForeignKey(
                blank=True,
                help_text="Small icon used in the browser tab. Should be square, and look good against light and dark backgrounds, similar to an app icon.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="favicon",
                to="wagtailimages.image",
                verbose_name="Favicon",
            ),
        ),
    ]
